In [6]:
from numpy import dot, exp, array, random

class neuronLayer():
    def __init__(self, numberOfNeuronLayers, inputsPerNeuron):
        self.synapticWeights = 2 * random.random((inputsPerNeuron, numberOfNeuronLayers))

class neuralNetwork():
    
    
    def __init__(self, layer1, layer2):
        self.layer1 = layer1
        self.layer2 = layer2
    
    #The sigmoid function
    
    def sigmoid(self,x):
        return 1/(1+exp(-x))
    
    def sigmoidDerivative(self,x):
        return x*(1-x)
        
    #Train the network through a process of trial and error while updating the weights at each step
    def train(self, trainIn, trainOut, maxIter):
        
        for iteration in range(maxIter):
            # Pass the training set through our neural network
            outputFromLayer1, outputFromLayer2 = self.think(trainIn)
            
            #Calculate the error from layer 2
            layer2error = trainOut - outputFromLayer2
            layer2Delta = layer2error * self.sigmoidDerivative(outputFromLayer2)
            
            #Calculate the error from layer 1
            layer1error = layer2Delta.dot(self.layer2.synapticWeights.T)
            layer1Delta = layer1error * self.sigmoidDerivative(outputFromLayer1)
            
            #Calcualate how much to adjust the weights
            
            layer1Adjustment = trainIn.T.dot(layer1Delta)
            layer2Adjustment = outputFromLayer1.T.dot(layer2Delta)
            
            #Adjust the weights
            
            self.layer1.synapticWeights += layer1Adjustment
            self.layer2.synapticWeights += layer2Adjustment
            
            
                     
    def think(self, inputs):
        outputFromLayer1 = self.sigmoid(dot(inputs, self.layer1.synapticWeights))
        outputFromLayer2 = self.sigmoid(dot(outputFromLayer1, self.layer2.synapticWeights))
        
        return outputFromLayer1, outputFromLayer2
    
    def printWeights(self):
        print('Layer 1 (4 neurons, each with 3 inputs):')
        print(self.layer1.synapticWeights)
        print("Layer 2 (1 neuron, with 4 inputs):")
        print(self.layer2.synapticWeights)

if __name__ == "__main__":
    
    #Seed the random generator
    
    random.seed(1)
    
    #Create layer 1 (4 neurons, each with 3 inputs)
    
    layer1 = neuronLayer(4,3)
    
    #Create layer 2 (a single neuron with 4 inputs)
    
    layer2 = neuronLayer(1,4)
    
    #Combine the layers to create a neural network
    
    neuralNetwork = neuralNetwork(layer1, layer2)
    
    print('Random Starting synaptic weights:')
    neuralNetwork.printWeights()
    
    
    #The training set; 7 examples each with three inputs
    trainIn = array([[0,0,1],[0,1,1],[1,0,1],[0,1,0],[1,0,0],[1,1,1],[0,0,0]])
    trainOut = array([[0,1,1,1,1,0,0]]).T
    
    #Train the neural network using the training set.
    #Do it 60,000 times and make small adjustments each time
    
    neuralNetwork.train(trainIn, trainOut, 60000)
    
    print("Stage 2 New Synaptic weights after training: ")
    neuralNetwork.printWeights()
    
    #Test the neural network with a new situation
    
    print("Stage 3 Considering a new situation [1,1,0] -> ?")
    hiddenState, outPut = neuralNetwork.think(array([1,1,0]))
    
    print(outPut)       

Random Starting synaptic weights:
Layer 1 (4 neurons, each with 3 inputs):
[[8.34044009e-01 1.44064899e+00 2.28749635e-04 6.04665145e-01]
 [2.93511782e-01 1.84677190e-01 3.72520423e-01 6.91121454e-01]
 [7.93534948e-01 1.07763347e+00 8.38389029e-01 1.37043900e+00]]
Layer 2 (1 neuron, with 4 inputs):
[[0.4089045 ]
 [1.75623487]
 [0.05477519]
 [1.34093502]]
Stage 2 New Synaptic weights after training: 
Layer 1 (4 neurons, each with 3 inputs):
[[ 6.47892716  5.3569066  -4.93989886  4.03848307]
 [-4.90353049  5.34871632  6.39687344  4.07017437]
 [ 0.78641328  0.04091763  0.85499938  1.69790731]]
Layer 2 (1 neuron, with 4 inputs):
[[-14.57942688]
 [ 12.05741367]
 [-14.58473645]
 [  8.18939311]]
Stage 3 Considering a new situation [1,1,0] -> ?
[0.02496571]
