In [16]:
from numpy import exp, dot, array, random
import time
class neuronLayer():
    
    def __init__(self, numberOfNeurons, inputsPerNeuron):
        self.synapticWeights = 2 * random.random((inputsPerNeuron, numberOfNeurons))

class neuralNetwork():
    
    def __init__(self, layer1, layer2):
        
        self.layer1 = layer1
        self.layer2 = layer2
        
        
        
        
    #The sigmoid function
    def sigmoid(self, x):
        return 1 / (1+exp(-x))
        
    #The sigmoid derivative
    def sigmoidDerivative(self, x):
        return x*(1-x)
      
    #The network
    def train(self, trainIn, trainOut, maxIter):
            
        #Passing the train inputs through the network
        start=  time.process_time()     
        for iteration in range(maxIter):
                
            output1, output2 = self.think(trainIn)
                
            # getting the error and the adjustment value
                
            error2 = trainOut - output2
            delta2 = error2 * self.sigmoidDerivative(output2)
                
            # getting the error and adjustment value for error1 
            # error1 is determined by looking at how much layer 1 contributed to the error / delta in layer 2
            #this is achieved by multiplying the delta in layer 2 by the weights in layer 1
            error1 = delta2.dot(self.layer2.synapticWeights.T) # TBC
            delta1 = error1 * self.sigmoidDerivative(output1)
                
            # Calculate by how much you adjust the weights
            layer1Adjustment = trainIn.T.dot(delta1)
            layer2Adjustment = output1.T.dot(delta2)
                
            #Adjust the weights
            self.layer1.synapticWeights += layer1Adjustment
            self.layer2.synapticWeights += layer2Adjustment
   
        print(time.process_time()- start)
    
    
    def think(self, inputs):
        output1 = self.sigmoid(dot(inputs, self.layer1.synapticWeights))
        output2 = self.sigmoid(dot(output1, self.layer2.synapticWeights))
            
        return output1, output2
            
            
    #The neural network prints its weights
        
    def printWeights(self):
        print("Layer 1: 4 neuron each with 4 inputs: ")
        print(self.layer1.synapticWeights)
            
        print("Layer 2: 1 neuron with 4 inputs: ")
        print(self.layer2.synapticWeights)
            

if __name__ == "__main__":
    
    #Seed the random generator
    
    random.seed(1)
    
    #Create the layers
    
    layer1 = neuronLayer(4,4)
    layer2 = neuronLayer(1,4)
    
    #Create the neural network
    
    neuralNetwork = neuralNetwork(layer1,layer2)
    
    print("Random Starting Synaptic weights")
    
    neuralNetwork.printWeights()
    
    trainIn = array([[0,1,1,1],[1,0,1,0],[1,0,1,0],[0,0,1,1],[1,1,1,1],[0,1,1,0],[1,0,0,1],[0,1,1,1],[0,1,1,1]])
    trainOut = array([[1,0,1,0,1,0,0,0,1]]).T
    
    neuralNetwork.train(trainIn, trainOut, 60000)
    
    print("Stage 2 Weights")
    
    neuralNetwork.printWeights()
    
    print("Stage 3 for a new siatuation")
    
    hState, output = neuralNetwork.think(array([[0,1,1,1]]))
    
    print(output)
                                   

Random Starting Synaptic weights
Layer 1: 4 neuron each with 4 inputs: 
[[8.34044009e-01 1.44064899e+00 2.28749635e-04 6.04665145e-01]
 [2.93511782e-01 1.84677190e-01 3.72520423e-01 6.91121454e-01]
 [7.93534948e-01 1.07763347e+00 8.38389029e-01 1.37043900e+00]
 [4.08904499e-01 1.75623487e+00 5.47751864e-02 1.34093502e+00]]
Layer 2: 1 neuron with 4 inputs: 
[[0.8346096 ]
 [1.11737966]
 [0.28077388]
 [0.39620298]]
5.459489999999995
Stage 2 Weights
Layer 1: 4 neuron each with 4 inputs: 
[[-0.63876753  6.07311882 -3.52308994  2.35496609]
 [ 8.39021154 -1.23502428  1.57507031  2.54357351]
 [ 0.82184987 -1.99623784  0.79242336  3.71004044]
 [-3.45090934  4.50332047 -1.43641378  3.53021843]]
Layer 2: 1 neuron with 4 inputs: 
[[  9.82492045]
 [  7.32092522]
 [ -3.44942274]
 [-12.3057168 ]]
Stage 3 for a new siatuation
[[0.67549753]]
