In [25]:
from numpy import exp, dot, array, random
import time

class neuronLayer():
    def __init__ (self, numberOfNeurons, inputPerNeuron):
        self.synapticWeights = 2 * random.random((inputPerNeuron, numberOfNeurons))
        
class neuralNetwork():
    def __init__(self, layer1, layer2):
        self.layer1 = layer1
        self.layer2 = layer2
        
    def sigmoid(self,x):
        return 1/(1+exp(-x))
    
    #The sigmoid derivative
    
    def sigmoidDerivative(self, x):
        return x *(1-x)
    
    #The neural Netwokr
    def train(self, trainIn, trainOut, maxIter):
        
        #Pass the input through the network
        for iterations in range(maxIter):
            
            #Determine the normalized output
            output1, output2 = self.think(trainIn)
            
            #Calculate the error for layer 2
            #Get the step for making the adjustment
            error2 = trainOut-output2
            delta2 = error2 * self.sigmoidDerivative(output2)
            
            
            #Calculate the error for layer 1
            error1 = delta2.dot(self.layer2.synapticWeights.T)
            delta1 = error1 * self.sigmoidDerivative(output1)
            
            #calculate the adjustments
            adjustment1 = trainIn.T.dot(delta1)
            adjustment2 = output1.T.dot(delta2)
            
            
            #Adjust the weights
            self.layer1.synapticWeights += adjustment1
            self.layer2.synapticWeights += adjustment2
            
            
    
    #The thinking function 
    def think(self, inputs):
        outputLayer1 = self.sigmoid(dot(inputs, self.layer1.synapticWeights))
        outputLayer2 = self.sigmoid(dot(outputLayer1, self.layer2.synapticWeights))
        
        return outputLayer1, outputLayer2
    
    #The Network print function
    def printWeights(self):
        print("Layer 1 Weights:")
        print(self.layer1.synapticWeights)
        print("Layer 2 Weights: ")
        print(self.layer2.synapticWeights)

if __name__== "__main__":
    
    #Seed the random generator
    random.seed(1)
    
    #Create Layer 1 
    layer1 = neuronLayer(5,5)
    #Create Layer 2
    layer2 = neuronLayer(1,5)
    
    #combine the layers to create a neural network
    neuralNet = neuralNetwork(layer1,layer2)
    
    #print the first random weights
    print("First stage random weights")
    neuralNet.printWeights()
    
    #Input the input and output data
    trainIn = array([[1,1,1,0,1],[0,1,1,0,1],[1,1,1,0,1],[1,0,1,0,1],[0,1,0,1,1],[0,1,1,1,0],
                     [1,1,0,1,0],[1,0,1,1,0],[1,0,0,0,1],[0,0,0,1,1]])
    trainOut = array([[0,1,0,0,1,0,1,1,0,1]]).T
    
    #pass the train in data through the network
    neuralNet.train(trainIn, trainOut, 60000)
    
    #print second stage weights after 60000 iterations
    print("Second stage weights after training: ")
    neuralNet.printWeights()
    
    #Consider a new situation and classify
    print("A new situation > [1,0,1,1,1]")
    hiddenstate, output = neuralNet.think(array([1,0,1,1,1]))
    print(output)
    print(hiddenstate)
    
    

First stage random weights
Layer 1 Weights:
[[8.34044009e-01 1.44064899e+00 2.28749635e-04 6.04665145e-01
  2.93511782e-01]
 [1.84677190e-01 3.72520423e-01 6.91121454e-01 7.93534948e-01
  1.07763347e+00]
 [8.38389029e-01 1.37043900e+00 4.08904499e-01 1.75623487e+00
  5.47751864e-02]
 [1.34093502e+00 8.34609605e-01 1.11737966e+00 2.80773877e-01
  3.96202978e-01]
 [1.60148914e+00 1.93652315e+00 6.26848356e-01 1.38464523e+00
  1.75277830e+00]]
Layer 2 Weights: 
[[1.78921333]
 [0.17008842]
 [0.07810957]
 [0.33966084]
 [1.75628501]]
Second stage weights after training: 
Layer 1 Weights:
[[-3.37057518  3.73499886  1.42363266 -1.70780219 -4.8355678 ]
 [ 1.10079309 -1.2592745  -0.24544825  4.62808916  1.69029539]
 [ 1.87289081  1.26927425 -0.61243131  5.26056846  2.27629937]
 [ 4.44420482  2.97940957 -1.70674498 -6.37340538  6.13458244]
 [-0.28063527 -2.26990901  4.55521784  3.06998454 -0.77834684]]
Layer 2 Weights: 
[[  3.94134195]
 [ -6.04096204]
 [  7.62000026]
 [-11.74836713]
 [  7.1235796